# i2b-chart/templates/auth-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
type: Opaque
data:
  # El valor es el contenido de tu archivo .htpasswd pero en base64
  # Podés generarlo en Linux con: cat nginx/.htpasswd | base64
  auth: {{ "tu_usuario:tu_password_encriptado" | b64enc }}